dynamixel_motors: [
{id: 1, joint_name: rotation1_joint,interface: PosVel, protocol: 2},
{id: 2, joint_name: shoulder1_joint,interface: PosVel, protocol: 2},
{id: 3, joint_name: shoulder2_joint,interface: PosVel, protocol: 2},
{id: 4, joint_name: rotation2_joint,interface: PosVel, protocol: 2},
{id: 5, joint_name: shoulder3_joint,interface: PosVel, protocol: 2},
{id: 6, joint_name: wrist_joint,interface: PosVel, protocol: 2},
{id: 7, joint_name: left_finger_joint,interface: PosVel, protocol: 2},
{id: 8, joint_name: right_finger_joint,interface: PosVel, protocol: 2},
{id: 9, joint_name: head_pan_joint,interface: Pos, protocol: 2},
{id: 10, joint_name: head_tilt_joint,interface: Pos, protocol: 2}
]

device: "/dev/USB2DYNAMIXEL"
device_baudrate: 1000000


