
robot_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  



arm_trajectory_controller:
  type: position_velocity_controllers/JointTrajectoryController
  joints:
     - rotation1_joint
     - shoulder1_joint 
     - shoulder2_joint 
     - rotation2_joint 
     - shoulder3_joint 
     - wrist_joint 
  publish_rate: 50
  constraints:
    goal_time: 15.5                   # Override default
    stopped_velocity_tolerance: 0.05 # Override default
    rotation1_joint: {trajectory: 10.2, goal: 10.2}
    shoulder1_joint: {trajectory: 10.2, goal: 10.2}
    shoulder2_joint: {trajectory: 10.2, goal: 10.2}
    rotation2_joint: {trajectory: 10.2, goal: 10.2}
    shoulder3_joint: {trajectory: 10.2, goal: 10.2}
    wrist_joint: {trajectory: 10.2, goal: 10.2}


gripper_controller:
 type: gripper_controllers/PosVelGripperController
 left_joint: 'left_finger_joint'
 right_joint: 'right_finger_joint'
 goal_tolerance: 0.005
 stalled_velocity_threshold: 0.005
 stall_timeout: 1.0
 joints_vel: 0.4
 action_monitor_rate: 50


torso_controller:
  type: position_controllers/JointPositionController
  joint: torso_joint
  
pan_tilt_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: ['head_pan_joint', 'head_tilt_joint']

mobile_base_controller:
  type        : "diff_drive_with_split_controller/DiffDriveController"
  left_wheel: 'left_wheel_joint'
  right_wheel: 'right_wheel_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.3284
  wheel_radius : 0.095
  slip_factor: 1.0

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 1.0

  enable_odom_tf: true

  # Base frame_id
  base_frame_id: base_footprint

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.8  # m/s
      min_velocity           : -0.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.22  # m/s^2
      min_acceleration       : -0.22 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.5  # rad/s^2
      

