#~ joy_node/dev: "/dev/input/js0"
#~ joy_node/autorepeat_rate: 20
teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /mobile_base_controller/cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 0
        target: angular.z
        scale: 1.0

  #~ joy_priority:
    #~ type: action
    #~ action_name: joy_priority_action
    #~ buttons: [7]
#~ 
  #~ joy_turbo_decrease:
    #~ type: action
    #~ action_name: joy_turbo_decrease
    #~ buttons: [1, 4, 5]
#~ 
  #~ joy_turbo_increase:
    #~ type: action
    #~ action_name: joy_turbo_increase
    #~ buttons: [3, 4, 5, 6]

